name: Deadheadlog
options:
  bundleIdPrefix: com.shimondeitel.deadheadlog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Deadheadlog:
    type: application
    platform: iOS
    sources:
      - path: Deadheadlog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.deadheadlog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Deadheadlog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  DeadheadlogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DeadheadlogTests
      - path: Deadheadlog.storekit
    dependencies:
      - target: Deadheadlog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.deadheadlog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  DeadheadlogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: DeadheadlogUITests
    dependencies:
      - target: Deadheadlog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.deadheadlog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Deadheadlog:
    build:
      targets:
        Deadheadlog: all
        DeadheadlogTests: [test]
        DeadheadlogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Deadheadlog.storekit
    test:
      config: Debug
      storeKitConfiguration: Deadheadlog.storekit
      targets:
        - DeadheadlogTests
        - DeadheadlogUITests
    archive:
      config: Release
